# Generated by Django 4.2 on 2023-04-18 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 13, 52, 12, 763872, tzinfo=datetime.timezone.utc)),
        ),
    ]
